COMPANY:
  TABLE_PATH: table/
  NAME_PATH: ../bin/company_name_number.csv
SAVE:
  ROOT_DIR: ../output/
  PDF_DIR: pdf/
  IMG_DIR: jpg/
CONSTANT:
  WEB_PATH: https://mops.twse.com.tw/mops/web/t100sb11
  DRIVER_PATH: ../bin/chromedriver
  YEAR_DEFUALT: 111